### ISSUE TITLE
Chat with us bot

### ISSUE THREAD

**Issue by TheTeamEngineer** [TheTeamEngineer/ElectroTech#2]
Create an automated messaging  'Chat with us' bot which replies predefined replies for some basic questions like Hello!, Help me, How can I contact?, How to add items in the cart? etc.  The bot should pop up on the landing page and should contain minimizing and close button.

**Comment by areeburrub** [comment]
I am Areeb a contributor at GSSOC'22 ,
I can add this feature to your website.

**Comment by TheTeamEngineer** [comment]
> I am Areeb a contributor at GSSOC'22 , I can add this feature to your website. Can I start working on this project ?

Yeah with it

**Comment by areeburrub** [comment]
I will be using DialogFlow for the chat-bot, is it okay ?

**Comment by areeburrub** [comment]
Can I talk with a maintainer I have to clarify some doubts

**Comment by Furquan712** [comment]
@areeburrub try to use discord for discussion

**Comment by areeburrub** [comment]
@Furquan712  can you please tell me on which server and what channel should I discuss about this project ?
