### ISSUE TITLE
Giving the About page a modern trendy look and feel  with image slider

### ISSUE THREAD

**Issue by Furquan712** [TheTeamEngineer/ElectroTech#20]
For eg: https://codepen.io/AndreCortellini/pen/QWrBza

**Comment by mansi0829** [comment]
sir i can add image slider can you please assign this issue to me

**Comment by Furquan712** [comment]
okay assigned , also give a modern trendy and attractive look  to About page

**Comment by mansi0829** [comment]
> okay assigned , also give a modern trendy and attractive look to About page

yes sure

**Comment by mansi0829** [comment]
sir bootstrap classes and even css is not working

**Comment by soumali28** [comment]
I would like to work on this issue under GSSoC.

**Comment by Furquan712** [comment]
@soumali28 assigned all the best
