### ISSUE TITLE
Home Responsive FAQ (Frequently Asked Question) Template Page,

### ISSUE THREAD

**Issue by TheTeamEngineer** [TheTeamEngineer/ElectroTech#7]
make it on above Home Page Footer 
For eg: https://codepen.io/owaiswiz/pen/oNXBvLy

**Comment by sulogna2001** [comment]
Hey Can I work on this issue under Gssoc22

**Comment by TheTeamEngineer** [comment]
Assigned ,

**Comment by sulogna2001** [comment]
@TheTeamEngineer should I be making exact same design as given one or I can modify by myself also?

**Comment by sulogna2001** [comment]
@TheTeamEngineer  hey is this issue can be calculated under GSSOC22?

**Comment by sulogna2001** [comment]
@TheTeamEngineer  I created a PR for this issue

**Comment by Furquan712** [comment]
> @TheTeamEngineer I created a PR for this issue kindly review that

Reviewed ,Nice work
